#!/usr/bin/env python3
"""CODEX-089: Browser-openable PHI-false HTML show-card from hospital-demo-report.json.

RUO / Shadow · clinical_validation=false · synthetic/local only.
Never embeds waveforms, patient identifiers, or cloud URIs.
Reuses gate checks from the Markdown show-card generator.
"""

from __future__ import annotations

import argparse
import html
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any

_MD_SCRIPT = Path(__file__).resolve().parent / "generate_hospital_demo_showcard.py"


def _load_md_gates():
    spec = importlib.util.spec_from_file_location("hospital_demo_showcard_md", _MD_SCRIPT)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to load {_MD_SCRIPT}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def render_showcard_html(report: dict[str, Any]) -> str:
    md = _load_md_gates()
    md._require_gates(report)
    safe = {k: report[k] for k in md.ALLOWED_TOP_KEYS if k in report}
    alignment = safe.get("alignment_qc") or {}
    replay = safe.get("replay_qc") or {}
    export = safe.get("local_export") or {}

    def cell(value: Any) -> str:
        return html.escape(str(value))

    channels = ", ".join(alignment.get("checked_channels") or [])
    rows = [
        ("status", safe.get("status")),
        ("path", safe.get("path")),
        ("mode", safe.get("mode")),
        ("intended_use", safe.get("intended_use")),
        ("clinical_validation", safe.get("clinical_validation")),
        ("contains_phi", safe.get("contains_phi")),
        ("synthetic_only", safe.get("synthetic_only")),
        ("case_id", safe.get("case_id")),
        ("seed", safe.get("seed")),
        ("duration_seconds", safe.get("duration_seconds")),
    ]
    gate_rows = "\n".join(
        f"<tr><th>{cell(k)}</th><td><code>{cell(v)}</code></td></tr>" for k, v in rows
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>T21 Path B Hospital Demo — Show Card</title>
  <style>
    :root {{ font-family: system-ui, sans-serif; color: #122; background: #f7f8fa; }}
    body {{ max-width: 44rem; margin: 2rem auto; padding: 0 1rem 3rem; }}
    .card {{ background: #fff; border: 1px solid #d9dee7; border-radius: 12px; padding: 1.25rem 1.5rem; box-shadow: 0 1px 2px rgba(0,0,0,.04); }}
    h1 {{ font-size: 1.35rem; margin: 0 0 .35rem; }}
    .banner {{ color: #334; font-size: .95rem; margin-bottom: 1rem; }}
    table {{ width: 100%; border-collapse: collapse; margin: .75rem 0 1.25rem; }}
    th, td {{ text-align: left; padding: .45rem .35rem; border-bottom: 1px solid #e6e9ef; vertical-align: top; }}
    th {{ width: 42%; color: #445; font-weight: 600; }}
    code {{ font-size: .92em; }}
    ul {{ padding-left: 1.2rem; }}
    .muted {{ color: #566; font-size: .9rem; }}
  </style>
</head>
<body>
  <article class="card">
    <h1>T21 Path B Hospital Demo — Show Card</h1>
    <p class="banner"><strong>RUO / Shadow</strong> · <code>clinical_validation=false</code> · PHI-false · synthetic only</p>
    <h2>Gates</h2>
    <table>
      <tbody>
{gate_rows}
      </tbody>
    </table>
    <h2>Alignment / QC</h2>
    <ul>
      <li>alignment status: <code>{cell(alignment.get("status"))}</code></li>
      <li>channels: <code>{cell(channels)}</code></li>
      <li>events_processed: <code>{cell(replay.get("events_processed"))}</code></li>
      <li>quality_usable: <code>{cell(replay.get("quality_usable"))}</code></li>
      <li>baseline_calibrated: <code>{cell(replay.get("baseline_calibrated"))}</code></li>
      <li>timestamp_synchronized: <code>{cell(replay.get("timestamp_synchronized"))}</code></li>
    </ul>
    <h2>Local export (metadata only)</h2>
    <ul>
      <li>includes_phi: <code>{cell(export.get("includes_phi"))}</code></li>
      <li>includes_waveforms: <code>{cell(export.get("includes_waveforms"))}</code></li>
      <li>content_scope: <code>{cell(export.get("content_scope"))}</code></li>
      <li>jsonl_path: <code>{cell(export.get("jsonl_path"))}</code></li>
    </ul>
    <h2>Not included</h2>
    <ul>
      <li>VitalDB / CapnoBase / PulseDB / MIMIC</li>
      <li>Raw waveforms or PHI</li>
      <li>Dosing, alerts, closed-loop, or clinical claims</li>
      <li>PROXY public benches (BIDMC / MIT-BIH / Fantasia) — labeled <strong>PROXY</strong> separately</li>
    </ul>
    <p class="muted">Generated by <code>scripts/generate_hospital_demo_showcard_html.py</code> · open this file in a browser.</p>
  </article>
</body>
</html>
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a PHI-false hospital demo HTML show-card (browser-openable)."
    )
    parser.add_argument(
        "report_json",
        type=Path,
        help="Path to hospital-demo-report.json from scripts/run_hospital_demo.sh",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="HTML output path (default: <report_dir>/showcard.html)",
    )
    args = parser.parse_args(argv)
    report = json.loads(args.report_json.read_text(encoding="utf-8"))
    if not isinstance(report, dict):
        raise SystemExit("report JSON must be an object")
    try:
        card = render_showcard_html(report)
    except ValueError as exc:
        print(json.dumps({"status": "FAIL_CLOSED", "error": str(exc)}), file=sys.stderr)
        return 2
    out = args.output
    if out is None:
        out = args.report_json.resolve().parent / "showcard.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(card, encoding="utf-8")
    print(str(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
